### ISSUE TITLE
复杂表头的时候，样式会错乱

### ISSUE THREAD

**Issue by windy532** [wenzhixin/bootstrap-table-fixed-columns#14]
多级表头的时候，表格样式出现混乱

**Comment by sk8yuck** [comment]
一样的问题，不过看了源码以后发现似乎是涉及到有两行表头的表格都会出问题，第二行表头被当成了Body

**Comment by ycycorona** [comment]
嵌套表头格式错乱 坐等大神更新修复

**Comment by ycycorona** [comment]
嵌套表头样式错乱 希望大神修复

**Comment by lancui1110** [comment]
貌似设置了最后一列的rowspan为1解决了
![image](https://cloud.githubusercontent.com/assets/8346809/23694842/139ad384-0417-11e7-9c06-90b76caf0d7b.png)
![image](https://cloud.githubusercontent.com/assets/8346809/23694915/84a4297c-0417-11e7-92e1-4ca4e69e526c.png)

**Comment by xlsunnb** [comment]
我仍旧没能解决这个问题，复杂表头的情况。
@lancui1110 仁兄给的解决方案，我在有三层组合表头的情况下，还是有问题。
<img width="523" alt="qq20170729-021225 2x" src="https://user-images.githubusercontent.com/30534646/28731028-e777a4cc-7404-11e7-96e8-0cec34e119ea.png">

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中，该问题已修复。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
