### ISSUE TITLE
”Fixed Columns“ doesn't work with footer

### ISSUE THREAD

**Issue by MyronJi** [wenzhixin/bootstrap-table-fixed-columns#17]
”Fixed Columns“ doesn't work with footer.
![20160918190305](https://cloud.githubusercontent.com/assets/20621646/18617127/4b58e984-7dfb-11e6-8274-5bcc4379c811.jpg)

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table).
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
