### ISSUE TITLE
能在初始化后设置`fixed-table-body-columns`的`heigth`和`top`吗

### ISSUE THREAD

**Issue by cgfeel** [wenzhixin/bootstrap-table-fixed-columns#19]
我发现要使用这个扩展，必须设置 `data-height`，而我需要自适应高度；

自适应高度的话，会发现`fixed-table-body-columns`这层div的`heigth`和`top`都不正确，请问我能在初始化后设置`heigth`和`top`这个样式吗？

不然没办法用了。

**Comment by cgfeel** [comment]
另外包括官方的演示中，看到的表格也对不齐

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
