### ISSUE TITLE
Scrollbar is hidden under fIxed columns.

### ISSUE THREAD

**Issue by Loecha** [wenzhixin/bootstrap-table-fixed-columns#2]
Hi, wenzhixin.
Scrollbar bottom is hidden under fIxed columns.
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html

**Comment by kimaina** [comment]
Has this issue been handled/solved?

**Comment by serlogo53** [comment]
Also i haver same problem.

**Comment by kimaina** [comment]
this fixed this issue on my end:

``` javascript
          height: 550,
          fixedColumns: true,
          fixedNumber:1,
          onPostBody:function(){
            //please make sure you calibrate results[0].style.maxHeight with relation to height (550)
            //maxHeight=(height/2)+3
            var results = document.getElementsByClassName("fixed-table-body-columns");
            results[0].style.maxHeight='228px';
          }
```

From this insight, we can create a fix in the main wenzhixin/bootstrap-table-fixed-columns repo on this file bootstrap-table-fixed-columns.js

**Comment by kis8ya** [comment]
It should be `tableHeight - horizontalScrollBarHeight` instead of `- 2`, you can't fix it with constants like 228px  ([here](https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/1.0.0/bootstrap-table-fixed-columns.js#L115)).

**Comment by Loecha** [comment]
This is my solution for it: [Modification for "bootstrap-table-fixed-columns"](https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/3#issuecomment-240017617)

**Comment by wesleywong** [comment]
any solution for this? Fixed column still unable to scroll (vertical) the actual table.

**Comment by wenzhixin** [comment]
Merged.
