### ISSUE TITLE
没有横向滚动条时 表头与表格数据不对齐 已自己解决

### ISSUE THREAD

**Issue by lwjandmy** [wenzhixin/bootstrap-table-fixed-columns#20]
问题复现:

在官方"Fixed height"例子中:
http://jsfiddle.net/wenyi/e3nk137y/2954/

修改
.description {
    width: 500px;
}
把500px变成50px

会发现表头"Name"与数据"bootstrap-table"不对齐.

---

解决方法:

修改bootstrap-table-fixed-columns.js
在位置:
            that.$fixedHeader.find('th[data-field="' + visibleFields[index] + '"]')
                .find('.fht-cell').width($this.innerWidth());
增加代码:
that.$fixedHeader.find('th[data-field="' + visibleFields[index] + '"]').width($this.innerWidth());

**Comment by wenzhixin** [comment]
谢谢反馈，已修改。
