### ISSUE TITLE
若果window resize的話，fixed column就不會再移動

### ISSUE THREAD

**Issue by airicyu** [wenzhixin/bootstrap-table-fixed-columns#21]
我是用chrome測試的。
http://jsfiddle.net/wenyi/e3nk137y/2954/
在這個sample裡，你把window resize一下，然後veritical scrolling時，fixed column都不會跟隨移動。

**Comment by koucxz** [comment]
You just need to resize the table when window resize,use 
               $(window).resize(function () {
                    $('#tableId').bootstrapTable('resetView');
                });
this function set a listener , when window resize, table resized,too.

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中，该问题已修复。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
