### ISSUE TITLE
(Suggestion) Only following css tweak was good enough for me without including this plugin

### ISSUE THREAD

**Issue by harshvchawla** [wenzhixin/bootstrap-table-fixed-columns#22]
`.table > thead > tr > th {
    padding-left: 40px !important;
}

.table > tbody > tr > td:first-child {
    position: absolute;
    width: 40px;
}`

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
