### ISSUE TITLE
固定列

### ISSUE THREAD

**Issue by sunshinefull** [wenzhixin/bootstrap-table-fixed-columns#23]
如何固定头两列和最后两列，中间可以滚动

**Comment by langyan1022** [comment]
https://github.com/langyan1022/bootstrap-table-fixed-columns
自己修改了下，可以试试

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中，已支持左右列。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
