### ISSUE TITLE
Problem with toggle Columns

### ISSUE THREAD

**Issue by Loecha** [wenzhixin/bootstrap-table-fixed-columns#24]
If I use this Plugin, have a Problem with Hide/Show of Columns with Columns-Toggler. This is Problem description: 
[jsfiddle-Problem](https://jsfiddle.net/g6w09w2y/3/)
- First two Columns are fixed
- Data for Cell0 und Cell1 habe a large text
- Now, deselect first Column
- You can sie, that old copy of Table is available and visible.
- This is a Problem.

Resolving is, 
[jsfiddle-Resolving ](https://jsfiddle.net/g6w09w2y/4/)
removing all elements of Fixed-Pluggin before Initialized.

**This Modification resolve not only this problem, but also protect for Memory leaks during toggling of columns.**

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
