### ISSUE TITLE
set fixed columns other column width % It doesn't work.

### ISSUE THREAD

**Issue by apchenjun** [wenzhixin/bootstrap-table-fixed-columns#25]
set fixed columns other column width % It doesn't work.

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
