### ISSUE TITLE
左右列冻结支持

### ISSUE THREAD

**Issue by langyan1022** [wenzhixin/bootstrap-table-fixed-columns#26]
没权限pull request ，fork了一个，

在作者的基础上修改了下，如果作者有意见请通知我删除，打扰了

分享见我的库
https://github.com/langyan1022/bootstrap-table-fixed-columns

**Comment by apchenjun** [comment]
用了一下你的 发现也存在问题 当固定表格高度 有上下滚动条时也 错位 而且如何我表格有自定义样式固定列后样式不能应用 也就是固定列和表格的样式不一样 横向有滚动条 拖到固定列也被挡住了

**Comment by langyan1022** [comment]
你可以看着修改下 @apachenjun

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中，已支持左右列。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
