### ISSUE TITLE
Table height wrong when no horizontal scroll

### ISSUE THREAD

**Issue by jonathangreco** [wenzhixin/bootstrap-table-fixed-columns#28]
![fixed columns when too few columns](https://user-images.githubusercontent.com/1587180/29459786-a3864b7a-8425-11e7-812f-de6ad77e9ff9.png)

When we use bootstrap-table-fixed-columns, with columns declared dynamically, we can't  know in advance how much columns we will have. 
https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js#L135

Then, with those assertions this line is a problem because when we have the plugin activated, with too few columns, the table height is substracted by -14 with no reason (we have no horizontal-scroll).

The solution is :
- We must check before if the scroll is up, and then substract -14, if the scroll is not here, table height with no substraction must be declared.

How can we check if the scroll is up ?

**Comment by jonathangreco** [comment]
```JS
var that = this,
            top = -(parseInt(this.$el.css('margin-top')) - 2),
            height = 0;

        // the fixed height should reduce the scorll-x height
        if (this.$tableBody.hasHorizontalScrollBar()) {
            height = this.$tableBody.height() - 19;
        }
``````
 With this new function :`

````JS
    $.fn.hasHorizontalScrollBar = function() {
        return this.get(0) ? this.get(0).scrollWidth > this.innerWidth() : false;
    };

````
Correct my issue.

**Comment by jonathangreco** [comment]
Pull request 29 is on the way for fixing this.

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
