### ISSUE TITLE
Sort under fixed columns does not work.

### ISSUE THREAD

**Issue by Loecha** [wenzhixin/bootstrap-table-fixed-columns#3]
Hi, wenzhixin.
Thanks for new Plugin. It is exactly what i need.
But sort under fixed columns does not work.
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html

**Comment by djhvscf** [comment]
I think this [issue](https://github.com/wenzhixin/bootstrap-table/issues/2001) is related to this one because the fixed columns table is not fired the events.. that is because the bootstrap-table is not binding the event to the fixed columns table..  @TAlProg

**Comment by Loecha** [comment]
This is my Modification for "bootstrap-table-fixed-columns" [Modification under jsFiddle](https://jsfiddle.net/g6w09w2y/2/) it work for my.

This Mode Fixed following Issues:
[Sort under fixed columns does not work. ](https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/3)
[Scrollbar is hidden under fIxed columns. ](https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/2)

Tested under:
Windows 10 (64Bit)
Firefox 48.0, Chrome 52.0.2743.116 m, IE11.545, Edge 25.10586.0.0

**Comment by makombe** [comment]
if this can be merged it will be useful. I need to sort the fixed columns

**Comment by wenzhixin** [comment]
Merged.
