### ISSUE TITLE
Add way to freeze column at right side

### ISSUE THREAD

**Issue by michaelsogos** [wenzhixin/bootstrap-table-fixed-columns#30]
Dear @wenzhixin ,

Can you improve this extension to freeze right columns?
The general idea is to use negative number on `data-fixed-number` or `fixedNumber ` option, so:
* When it is 1 or greater left columns will be freezed, like now
* When it is 0 no columns will be freezed but just headers, like now
* When it is -1 or less right columns will be freezed

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
