### ISSUE TITLE
thead和tbody无法对齐

### ISSUE THREAD

**Issue by miqike** [wenzhixin/bootstrap-table-fixed-columns#31]
使用冻结列后表头和数据无法对齐，而且和图标一起使用的话，当拉滚动条时，图标会移动

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
