### ISSUE TITLE
Filtering doesn't work for the fixed column

### ISSUE THREAD

**Issue by gmathurusc** [wenzhixin/bootstrap-table-fixed-columns#32]
When we add `data-fixed-columns="true"` to the table, the filtering(`data-filter-control="input"`) for that column doesn't work.

**Comment by sunilsr1986** [comment]
Any updates on the #15

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
