### ISSUE TITLE
作者这个插件有很多样式问题和BUG还修复吗

### ISSUE THREAD

**Issue by apchenjun** [wenzhixin/bootstrap-table-fixed-columns#33]
在实际的项目使用中发现作者这个插件 存在很多问题 样式错乱 对不齐 固定列后 固定列的样式不能应用表格的样式 什么滚动条被挡住 等等
特别是复杂表格头和有自定义样式的时候 这个插件乱的一团糟 我看这里下面反馈这个插件有问题的不是一个两个
望作者 修复

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
