### ISSUE TITLE
Fixed height with fixed column's scrolling issue

### ISSUE THREAD

**Issue by wesleywong** [wenzhixin/bootstrap-table-fixed-columns#34]
Fixed height with fixed column that unable to scroll actual table (vertical). Understand fixed column is overlay in front of actual table. Is there a way we can scroll(vertical) actual table when mouse within fixed columns area.

demo sample: http://jsfiddle.net/wenyi/e3nk137y/2954/

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
