### ISSUE TITLE
checkbox列在设置为冻结列后多个勾选获取选择列失效

### ISSUE THREAD

**Issue by MiNiYoBo** [wenzhixin/bootstrap-table-fixed-columns#36]
第一列为checkbox的多选table，checkbox列包含在冻结列中，则勾选的数据无法通过getSelections方法获取到选中行数据。
发现是fixed列是在绑定行选择事件后再添加的，没有绑定上选中事件，固选中行后选中状态未变更，进而无法获取选中数据。
现在已使用笨方法在fixed列添加后，重新绑定选中事件，可以解决此问题。

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
