### ISSUE TITLE
固定表头后，合并单元格跨两行的固定表头被重复显示

### ISSUE THREAD

**Issue by wuguzaliang** [wenzhixin/bootstrap-table-fixed-columns#37]
如图：
![1](https://user-images.githubusercontent.com/17598406/40224889-2994d5ae-5aba-11e8-8389-7048b6bd6fa5.jpg)
![2](https://user-images.githubusercontent.com/17598406/40224896-2e00bad6-5aba-11e8-9763-cfc305741731.jpg)

页面代码片段：
========================
 
![3](https://user-images.githubusercontent.com/17598406/40225076-acc250be-5aba-11e8-980c-38e551f86934.jpg)

==================

**Comment by wuguzaliang** [comment]
找到问题的原因是： 当表头合并单元格的列数量多于固定列的数量时，合并单元格的效果失效。如果数量相同，则工作正常。比如：固定列两列，合并单元格Rowspan=2有两列，显示正常。如果合并单元格Rowspan=2有四列，则显示不正常，合并单元格刚失效

**Comment by wuguzaliang** [comment]
![4](https://user-images.githubusercontent.com/17598406/40290249-683e62a2-5cef-11e8-9949-eba7b4db2468.jpg)

**Comment by wuguzaliang** [comment]
![111](https://user-images.githubusercontent.com/17598406/40836067-0178893a-65c8-11e8-973c-a4e307e0e3b4.gif)
只有固定列列数与合并单元格的列数一致，是完全work的。

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
