### ISSUE TITLE
加载数据量过大时候，冻结列会错乱

### ISSUE THREAD

**Issue by horanly** [wenzhixin/bootstrap-table-fixed-columns#38]
1、冻结列在ie下有兼容
2、会出现重复的表头
3、冻结列之后，左面的列高和右面的列高不一样

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
