### ISSUE TITLE
错位严重

### ISSUE THREAD

**Issue by lymanzhao** [wenzhixin/bootstrap-table-fixed-columns#39]
![fix](https://user-images.githubusercontent.com/8308505/48699005-740fc080-ec23-11e8-94d0-1780b5254212.jpg)

100条，错位了11条，请问还在维护吗？

**Comment by ChihpingSun** [comment]
估计不会更新了，3年前的，都没看到提交过代码

**Comment by lymanzhao** [comment]
> 更新了，3年前的，都没看到提交过代码
正在测试迁移到react框架，可选比较多

**Comment by wenzhixin** [comment]
该插件已移动到 [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) 项目中。
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
