### ISSUE TITLE
Under IE11 does not work.

### ISSUE THREAD

**Issue by Loecha** [wenzhixin/bootstrap-table-fixed-columns#4]
Hi, Wenzhixin.
Unfortunately but under IE11 does not work.

**Comment by vlas-ilya** [comment]
In IE, the problem is that the fixed columns are blank.
If you're talking about this issue, then I think the problem is in the line 76, there is a problem with `$(this).clone()`.
I decided as follows:

```
var dataIndex = $tr.attr("data-index");
$tr = $("<tr></tr>");
$tr.attr("data-index", dataIndex);
```

instead of `$tr.html('');`
