### ISSUE TITLE
Why does every other even data say "Loading from AJAX request" while odd data displays?

### ISSUE THREAD

**Issue by kevin11h** [wenzhixin/bootstrap-table-fixed-columns#40]
@wenzhixin Why does every other even data say "Loading from AJAX request" while odd data displays?

![even-odd](https://user-images.githubusercontent.com/5397375/55833712-0a5a5b00-5acd-11e9-8943-5c2f6e1895d5.PNG)

Attach photo

**Comment by kevin11h** [comment]
(*And how to fix it, so that we can show the correct data?)

**Comment by wenzhixin** [comment]
The project has been moved to https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/fixed-columns.
Please use the latest version, if the problem exists, create an issue in https://github.com/wenzhixin/bootstrap-table/ repo.

**Comment by kevin11h** [comment]
@wenzhixin  Thank you.  Discovered the answer to my question -

1. Using your example code on [welcome table](https://examples.bootstrap-table.com/#welcome.html)

2. Switching to code view..

3. Section of code displays "loading from AJAX"

<pre>
$table.on('expand-row.bs.table', function (e, index, row, $detail) {
      if (index % 2 === 1) {
        $detail.html('Loading from ajax request...')
        $.get('LICENSE', function (res) {
          $detail.html(res.replace(/\n/g, '<br>'))
        })
      }
    })
</pre>

Great framework - More questions to come

**Comment by wenzhixin** [comment]
Because the LICENSE file is 404, this problem has been fixed quickly.
