### ISSUE TITLE
can you add fixed columns for table left and right 

### ISSUE THREAD

**Issue by zhaojianping** [wenzhixin/bootstrap-table-fixed-columns#5]
can you add fixed columns for table left and right side

**Comment by the-AjK** [comment]
up

**Comment by talatbaig** [comment]
any eta on this?

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
