### ISSUE TITLE
when fixed column is a button or icon,it works not well.

### ISSUE THREAD

**Issue by bmrainc** [wenzhixin/bootstrap-table-fixed-columns#8]
I set a button on the fixed column ,it appear another one.
![image](https://cloud.githubusercontent.com/assets/7332588/11336034/dcb1839e-921c-11e5-9865-5b0d1c932256.png)

**Comment by bmrainc** [comment]
It appears when you scorll the scorll bar.

**Comment by cxong** [comment]
http://jsfiddle.net/wjpuL66k/1/

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/djhvscf/wjpuL66k/2/

**Comment by bmrainc** [comment]
thks
